### ISSUE TITLE
I think you should apply for GitHub Sponsors

### ISSUE THREAD

**Issue by eddiejaoude** [BOLT04/BOLT04#1]
You do so much great open source work, you should apply... https://github.com/sponsors

GitHub takes no commission and even match everything you get 🎉

**Comment by BOLT04** [comment]
Thank you @eddiejaoude 😄, I never really thought about it that much I guess. For now, I'm not looking at getting money through open source contributions, I really just wanna code and be on GitHub haha.

Thank you for the idea and suggestion 👍

**Comment by BOLT04** [comment]
Hi @eddiejaoude 😃, I'll close this issue for now. If the idea comes up again in the future I'll consider applying 👍.
Thank you again for your support!

**Comment by eddiejaoude** [comment]
Sure 👍
