### ISSUE TITLE
Trailing ] at the end

### ISSUE THREAD

**Issue by RaisinTen** [BOLT04/BOLT04#2]
You have a really beautiful profile! :slightly_smiling_face:
Let's get rid of the little booboo here:
![bot](https://user-images.githubusercontent.com/42526976/93668232-ced90400-faa8-11ea-88fc-c595dad55f8e.png)
I think applying this change to the last line should fix it:
```diff
- ![BOLT04's Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=BOLT04&layout=compact)]
+ ![BOLT04's Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=BOLT04&layout=compact)
```
:smile:

**Comment by BOLT04** [comment]
Hi @RaisinTen 😃, thank you for raising this, I didn't see it 😅. 
I must have missed the notification so I only saw this today, but this was fixed in this PR: #3 👍
