### ISSUE TITLE
Join the Org

### ISSUE THREAD

**Issue by VasudevJaiswal** [BOLT04/BOLT04#4]
[Click Here](https://github.com/Jaidevstudio/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)

**Comment by BOLT04** [comment]
Hi @VasudevJaiswal, thank you for the invite but I'm not looking to join more orgs for now, as I want to focus on contributing to the ones I'm part of.
